
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Diler_Holding_Varlik_Envater.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ENVATER_TAKIP_DB
{

    public int ID { get; set; }

    public string PERSONEL_SICIL_NO { get; set; }

    public string PERSONEL_AD_SOYAD { get; set; }

    public string PERSONEL_BOLUMU { get; set; }

    public string PERSONEL_ALT_BOLUM { get; set; }

    public string PERSONEL_POZISYON { get; set; }

    public string ISYERI_LOKASYON { get; set; }

    public string BILGISAYAR_DOMAIN_GRUBU { get; set; }

    public string BILGISAYAR_MARKA { get; set; }

    public string BILGISAYAR_MODEL { get; set; }

    public string BILGISAYAR_ADI { get; set; }

    public string BILGISAYAR_IP_ADRESI { get; set; }

    public string BILGISAYAR_MAC_ADRESI { get; set; }

    public string BILGISAYAR_ISLETIM_SISTEMI { get; set; }

    public string BILGISAYAR_TUTANAK_DURUMU { get; set; }

    public string BILGISAYAR_TESLIM_DURUMU { get; set; }

    public string BILGISAYAR_ACIKLAMA { get; set; }

    public string BILGISAYAR_RAM { get; set; }

    public string BILGISAYAR_ISLEMCI { get; set; }

    public string BILGISAYAR_SERI_NO { get; set; }

    public string MONITOR_MARKA { get; set; }

    public string MONITOR_MODEL { get; set; }

    public string MONITOR_SERI_NO { get; set; }

    public string MONITOR_INCH { get; set; }

    public string MONITOR_TESLIM_DURUMU { get; set; }

    public string MONITOR_TUTANAK_DURUMU { get; set; }

    public string MONITOR_ACIKLAMA { get; set; }

    public string YAZICI_MARKA { get; set; }

    public string YAZICI_MODEL { get; set; }

    public string YAZICI_SERI_NO { get; set; }

    public string YAZICI_TONER_KARTUS_KODU { get; set; }

    public string YAZICI_BAGLI_KULLANICI { get; set; }

    public string YAZICI_USB { get; set; }

    public string YAZICI_IP_ADRESI { get; set; }

    public string YAZICI_MUREKKEP_TURU { get; set; }

    public string YAZICI_TESLIM_DURUMU { get; set; }

    public string YAZICI_TUTANAK_DURUMU { get; set; }

    public string YAZICI_ACIKLAMA { get; set; }

    public string YAZILIM_OFFICE_TEAMS_KULLANICI_ADI { get; set; }

    public string YAZILIM_OFFICE_TEAMS_MS_365_STATU { get; set; }

    public string YAZILIM_OFFICE_TEAMS_TEAMS_STATU { get; set; }

    public string YAZILIM_OFFICE_TEAMS_SIFRE { get; set; }

    public string YAZILIM_OFFICE_TEAMS_ALTERNATIF_SIFRE { get; set; }

    public string SAP_MODUL { get; set; }

    public string SAP_EMAIL_ADRES { get; set; }

    public string SAP_YETKILENDIRME { get; set; }

    public string SAP_KULLANICI_KODU { get; set; }

    public string SAP_PAROLA { get; set; }

    public string SAP_LOGONA_NAME { get; set; }

    public string SAP_SCN_NAME { get; set; }

    public string SAP_ACIKLAMA { get; set; }

    public string VINN_MARKA { get; set; }

    public string VINN_MODEL { get; set; }

    public string VINN_HAT_NUMARASI { get; set; }

    public string VINN_SERI_NO { get; set; }

    public string VINN_PIN_NO { get; set; }

    public string VINN_TESLIM_DURUMU { get; set; }

    public string VINN_TUTANAK_DURUMU { get; set; }

    public string VINN_ACIKLAMA { get; set; }

}

}
