
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Diler_Holding_Varlik_Envater.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOGIN
    {

        public int ID { get; set; }
        [Required(ErrorMessage = "E mail adresi zorunludur.")]
        [DataType(DataType.EmailAddress)]
        public string KULLANICI_ADI { get; set; }

        [Required(ErrorMessage = "Parola zorunludur !!")]
        [DataType(DataType.Password)]
        public string PAROLA { get; set; }

    }

}
